<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Qhapaq.Abstractions\Qhapaq.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\src\Qhapaq.DAL\Qhapaq.DAL.csproj" />
  </ItemGroup>
</Project>